# Generated by Django 5.2.8 on 2025-11-13 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageassessment',
            name='flood_depth_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth of flood water in meters at the household location', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='household',
            name='house_height_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height of the house in meters', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='household',
            name='house_width_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width of the house in meters', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='household',
            name='is_4ps_recipient',
            field=models.BooleanField(default=False, help_text='Whether the household is a 4Ps (Pantawid Pamilyang Pilipino Program) recipient'),
        ),
    ]
